config/routes.rb
Rails.application.routes.draw do
    root 'questions#index'
    get '/questions' => 'questions#index'
    get '/questions/new' => 'questions#new' 
    get '/questions/:id' => 'questions#show', as: :question
    post '/questions' => 'questions#create'
    get 'questions/:id/edit' => 'questions#edit', as: :edit_question
    patch 'questions/:id' => 'questions#update'
    delete 'questions/:id' => 'questions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
    
  end

  def show
    id = params[:id]
    @question =  Question.find(id)
  end

  def new
      @question= Question.new
  end

  def create
    @question = Question.new
    @question.body = params[:question][:body]
    @question.answered = params[:question][:answered]
    @question.save
    redirect_to '/questions'
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    @question.body = params[:question][:body]
    @question.answered = params[:question][:answered]
    @question.save
    redirect_to '/questions'
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    redirect_to '/questions'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quora</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/create.html.erb
<h1>Questions#create</h1>
<p>Find me in app/views/questions/create.html.erb</p>

app/views/questions/destroy.html.erb
<h1>Questions#destroy</h1>
<p>Find me in app/views/questions/destroy.html.erb</p>

app/views/questions/edit.html.erb
<h1>Edit Question</h1>

<%= form_for @question do |f| %>
    <%= f.text_field(:body,{placeholder: "Question"}) %>
    <%= f.text_field(:answered,{placeholder: "Answered?"}) %>
    <%= f.submit "Edit" %>
<% end %>

app/views/questions/index.html.erb
<h1>Questions</h1>

<ul>
    <% for question in @questions%>
        <li><%= link_to(question.body,"/questions/#{question.id}") %> </li>
    <% end %>
</ul>

app/views/questions/new.html.erb
<h1>New Question</h1>
  <%= form_for @question do |f| %>
    <%= f.text_field(:body,{placeholder: "Question"}) %>
    <%= f.submit "Ask" %>
<% end %>

app/views/questions/show.html.erb
<h1>Question</h1>

<h3>
    <%= @question.body %>
</h3>
<h3>
Answered?: 
    <%= @question.answered %>
</h3>

<h4><%= time_ago_in_words @question.created_at %> ago</h4>

<%= link_to "Edit", edit_question_path(@question) %>

<%= link_to "Delete", question_path(@question), method: "delete" %>

app/views/questions/update.html.erb
<h1>Questions#update</h1>
<p>Find me in app/views/questions/update.html.erb</p>